services:
  db:
    image: supabase/postgres:14.1.0.34
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./supabase/migrations:/docker-entrypoint-initdb.d

  studio:
    image: supabase/studio:latest
    ports:
      - "54323:3000"
    environment:
      SUPABASE_URL: http://kong:8000
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db

  kong:
    image: kong:2.8.1-alpine
    ports:
      - "54321:8000"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
    depends_on:
      - db

  meta:
    image: supabase/postgres-meta:0.58.0
    ports:
      - "8080:8080"
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: postgres
    depends_on:
      - db