-- Add position and dimension columns to node table
ALTER TABLE public.node
ADD COLUMN IF NOT EXISTS x FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS y FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS width INTEGER DEFAULT 200,
ADD COLUMN IF NOT EXISTS height INTEGER DEFAULT 200;